source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform:ios, '8.0'

target 'HDBaseProject_Example' do
    pod 'HDBaseProject', :path => "../"
end

target 'HDBaseProject_Tests' do
    pod 'HDBaseProject', :path => "../"
end

