source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HDBaseProject_Example', :exclusive => true do
    pod 'HDBaseProject', :path => "../"
end

target 'HDBaseProject_Tests', :exclusive => true do
    pod 'HDBaseProject', :path => "../"
end

