# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
# * https://docs.travis-ci.com/user/languages/objective-c/

language: objective-c
osx_image: xcode11.4
# path to your xcodeproj folder
# xcode_workspace: Example/HDBaseProject.xcworkspace
# xcode_scheme: HDBaseProject-Example
# xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
# podfile: path/to/Podfile
# install: make get-deps


# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/HDBaseProject.xcworkspace -scheme HDBaseProject-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
